# This is a generated file. Not intended for manual editing.
version: "3.7"
services:
  productcatalogservice:
    build:
      context: "/Users/omrishapira/Desktop/ProductCatalogService"
      dockerfile: "ProductCatalogService/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "productcatalogservice:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "/Users/omrishapira/.nuget/packages:/root/.nuget/packages"
    - "/Users/omrishapira/Desktop/ProductCatalogService/ProductCatalogService:/app:rw"
    - "/Users/omrishapira/Desktop/ProductCatalogService:/src:rw"
    - "/Users/omrishapira/.local/share/JetBrains/RiderRemoteDebugger/2023.3.3/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/omrishapira/Library/Logs/JetBrains/Rider2023.3/DebuggerWorker/JetBrains.Debugger.Worker.2024_7_11_21_02_25:/var/opt/rider-debugger:rw"
    working_dir: "/app"
